import uuid

# Запрос с исходными данными
query = """
  ('Tower of London', 1, 'Explore the historic landmarks, bustling markets, and diverse culture of London, in the best tower of United Kingdom.', 1, 'b73d17d5-2b2e-4f96-89c8-2a7f11eb9a47.png'),
  ('British Museum', 1, 'Discover the worlds history and culture in one of the largest and most comprehensive museums in the world.', 1, 'british_museum.png'),
  ('Buckingham Palace', 1, 'Experience the grandeur and elegance of the British monarchy at Buckingham Palace.', 1, 'buckingham_palace.png'),
  ('London Eye', 1, 'Enjoy breathtaking views of London from this iconic Ferris wheel.', 1, 'london_eye.png'),
  ('Tower Bridge', 1, 'Marvel at the engineering masterpiece that is Tower Bridge, an iconic symbol of London.', 1, 'tower_bridge.png'),
  ('Tokyo Disneyland', 2, 'Experience the magic of Disney in the heart of Tokyo at Tokyo Disneyland.', 1, 'tokyo_disneyland.png'),
  ('Senso-ji Temple', 2, 'Immerse yourself in the rich history and culture of Japan at Tokyos oldest temple.', 1, 'sensoji_temple.png'),
  ('Shibuya Crossing', 2, 'Witness the organized chaos of the worlds busiest pedestrian crossing in Shibuya, Tokyo.', 1, 'shibuya_crossing.png'),
  ('Tsukiji Fish Market', 2, 'Indulge in the freshest seafood at the largest wholesale fish and seafood market in the world.', 1, 'tsukiji_fish_market.png'),
  ('Tokyo Tower', 2, 'Enjoy panoramic views of Tokyo from this iconic communications and observation tower.', 1, 'tokyo_tower.png'),
  ('State Hermitage Museum', 3, 'Explore one of the largest and oldest museums in the world, showcasing art and culture spanning centuries.', 1, 'state_hermitage_museum.png'),
  ('Church of the Savior on Spilled Blood', 3, 'Admire the stunning architecture and intricate mosaics of this iconic Russian Orthodox church.', 1, 'church_of_the_savior.png'),
  ('Peter and Paul Fortress', 3, 'Discover the history of Saint Petersburg at the original citadel of the city, now a cultural and historical landmark.', 1, 'peter_and_paul_fortress.png'),
  ('Nevsky Prospect', 3, 'Stroll along the vibrant main street of Saint Petersburg, lined with shops, restaurants, and historical buildings.', 1, 'nevsky_prospect.png'),
  ('Winter Palace', 3, 'Step into the opulent former official residence of the Russian emperors, now part of the Hermitage Museum complex.', 1, 'winter_palace.png'),
  ('Statue of Liberty', 4, 'Symbolizing freedom and democracy, the Statue of Liberty is a must-visit landmark in New York City.', 1, 'statue_of_liberty.png'),
  ('Central Park', 4, 'Escape the hustle and bustle of the city and enjoy the tranquility of Central Park, offering green spaces, lakes, and recreational activities.', 1, 'central_park.png'),
  ('Empire State Building', 4, 'Experience breathtaking views of the New York skyline from the top of this iconic Art Deco skyscraper.', 1, 'empire_state_building.png'),
  ('Times Square', 4, 'Immerse yourself in the vibrant energy of Times Square, known for its bright lights, theaters, and bustling atmosphere.', 1, 'times_square.png'),
  ('Metropolitan Museum of Art', 4, 'Discover a vast collection of art spanning thousands of years and cultures at the Metropolitan Museum of Art.', 1, 'metropolitan_museum.png'),
  ('Acadia National Park', 5, 'Experience the natural beauty of Maine at Acadia National Park, known for its rugged coastline, forests, and granite peaks.', 1, 'acadia_national_park.png'),
  ('Portland Head Light', 5, 'Admire the picturesque views of the Atlantic Ocean from this historic lighthouse, the oldest in Maine.', 1, 'portland_head_light.png'),
  ('Old Port', 5, 'Explore the charming cobblestone streets, boutiques, and restaurants of Old Port, a vibrant district in Portland, Maine.', 1, 'old_port.png'),
  ('Bar Harbor', 5, 'Discover the quaint seaside town of Bar Harbor, a gateway to Acadia National Park, offering shops, galleries, and fresh seafood.', 1, 'bar_harbor.png'),
  ('Cadillac Mountain', 5, 'Watch the sunrise from the highest peak on the East Coast of the United States at Cadillac Mountain in Acadia National Park.', 1, 'cadillac_mountain.png'),
  ('Old Town Market Square', 6, 'Experience the charm of Warsaws historic Old Town, with its colorful buildings, cobblestone streets, and lively atmosphere.', 1, 'old_town_market_square.png'),
  ('Royal Castle', 6, 'Step back in time and explore the Royal Castle, a symbol of Polands resilience and reconstruction after World War II.', 1, 'royal_castle.png'),
  ('Warsaw Uprising Museum', 6, 'Learn about the heroic struggle of the Polish resistance during the Warsaw Uprising of 1944 at this poignant museum.', 1, 'warsaw_uprising_museum.png'),
  ('Łazienki Park', 6, 'Relax in the green oasis of Łazienki Park, home to palaces, gardens, and the iconic Chopin Monument.', 1, 'lazienki_park.png'),
  ('Palace of Culture and Science', 6, 'Marvel at the imposing architecture of the Palace of Culture and Science, a Soviet-era skyscraper dominating Warsaws skyline.', 1, 'palace_of_culture_and_science.png'),
  ('Red Square', 7, 'Experience the heart of Moscow at Red Square, surrounded by iconic landmarks such as the Kremlin, St. Basils Cathedral, and the State Historical Museum.', 1, 'red_square.png'),
  ('Kremlin', 7, 'Explore the fortified complex of the Moscow Kremlin, home to the Russian president and a treasure trove of historical and cultural artifacts.', 1, 'kremlin.png'),
  ('Bolshoi Theatre', 7, 'Immerse yourself in the world of ballet and opera at the historic Bolshoi Theatre, one of the most renowned cultural institutions in Russia.', 1, 'bolshoi_theatre.png'),
  ('Gorky Park', 7, 'Enjoy outdoor recreation and entertainment in the sprawling Gorky Park, offering attractions such as amusement rides, art installations, and scenic promenades.', 1, 'gorky_park.png'),
  ('Moscow Metro', 7, 'Admire the stunning architecture and elaborate decorations of the Moscow Metro, often referred to as the "Palace of the People".', 1, 'moscow_metro.png'),
  ('Kinkaku-ji Temple', 8, 'Marvel at the shimmering golden pavilion of Kinkaku-ji Temple, set amidst beautiful gardens and reflecting ponds.', 1, 'kinkakuji_temple.png'),
  ('Fushimi Inari Taisha', 8, 'Walk through thousands of vermillion torii gates at Fushimi Inari Taisha, a sacred Shinto shrine dedicated to the god of rice and prosperity.', 1, 'fushimi_inari_taisha.png'),
  ('Arashiyama Bamboo Grove', 8, 'Stroll through the ethereal Arashiyama Bamboo Grove, a serene natural wonder just outside of Kyoto.', 1, 'arashiyama_bamboo_grove.png'),
  ('Kiyomizu-dera Temple', 8, 'Experience panoramic views of Kyoto from the wooden terrace of Kiyomizu-dera Temple, a UNESCO World Heritage Site.', 1, 'kiyomizu_temple.png'),
  ('Gion District', 8, 'Step into the traditional world of geisha and tea houses in the historic Gion District, known for its preserved machiya houses and cultural performances.', 1, 'gion_district.png'),
  ('Golden Gate', 9, 'Admire the impressive 12th-century fortifications of the Golden Gate, once the main entrance to the medieval city of Vladimir.', 1, 'golden_gate.png'),
  ('Assumption Cathedral', 9, 'Visit the magnificent Assumption Cathedral, a UNESCO World Heritage Site and one of the oldest and most important cathedrals in Russia.', 1, 'assumption_cathedral.png'),
  ('Dormition Monastery', 9, 'Discover the historic Dormition Monastery, founded in the 12th century and known for its beautiful architecture and religious significance.', 1, 'dormition_monastery.png'),
  ('Vladimir Suzdal Museum Reserve', 9, 'Explore the open-air museum of Vladimir Suzdal Museum Reserve, showcasing the rich cultural heritage of the Vladimir region.', 1, 'vladimir_suzdal_museum.png'),
  ('Church of the Intercession on the Nerl', 9, 'Marvel at the picturesque setting of the Church of the Intercession on the Nerl, a UNESCO World Heritage Site located on a scenic riverbank.', 1, 'intercession_church.png'),
  ('Edinburgh Castle', 10, 'Explore the iconic Edinburgh Castle, perched atop Castle Rock and offering panoramic views of the city.', 1, 'edinburgh_castle.png'),
  ('Royal Mile', 10, 'Wander along the historic Royal Mile, lined with medieval buildings, shops, and landmarks such as St. Giles Cathedral and the Palace of Holyroodhouse.', 1, 'royal_mile.png'),
  ('Arthurs Seat', 10, 'Hike to the summit of Arthurs Seat, an extinct volcano in Holyrood Park, for stunning views of Edinburgh and its surroundings.', 1, 'arthurs_seat.png'),
  ('National Museum of Scotland', 10, 'Discover Scotlands rich history, culture, and natural heritage at the National Museum of Scotland, home to a diverse collection of artifacts and exhibitions.', 1, 'national_museum_of_scotland.png'),
  ('The Scotch Whisky Experience', 10, 'Embark on a whisky journey at The Scotch Whisky Experience, where you can learn about Scotlands national drink and sample a selection of fine whiskies.', 1, 'scotch_whisky_experience.png'),
  ('Osaka Castle', 11, 'Step into the past at Osaka Castle, one of Japans most famous landmarks and a symbol of the citys rich history.', 1, 'osaka_castle.png'),
  ('Dotonbori', 11, 'Experience the vibrant nightlife and culinary delights of Dotonbori, a bustling entertainment district known for its neon lights, street food, and iconic landmarks.', 1, 'dotonbori.png'),
  ('Universal Studios Japan', 11, 'Immerse yourself in the world of movies and entertainment at Universal Studios Japan, featuring thrilling rides, shows, and attractions for all ages.', 1, 'universal_studios_japan.png'),
  ('Osaka Aquarium Kaiyukan', 11, 'Discover the wonders of the ocean at Osaka Aquarium Kaiyukan, one of the largest aquariums in the world, home to a diverse array of marine life.', 1, 'osaka_aquarium_kaiyukan.png'),
  ('Shitenno-ji Temple', 11, 'Explore one of Japans oldest Buddhist temples, Shitenno-ji Temple, a tranquil oasis in the heart of Osaka.', 1, 'shitennoji_temple.png'),
  ('Sochi Park', 12, 'Experience family-friendly fun at Sochi Park, an amusement park inspired by Russian fairy tales and legends, offering rides, shows, and attractions.', 1, 'sochi_park.png'),
  ('Olympic Park', 12, 'Explore the legacy of the 2014 Winter Olympics at Sochi Olympic Park, featuring sports venues, parks, and landmarks such as the Fisht Olympic Stadium.', 1, 'olympic_park.png'),
  ('Riviera Park', 12, 'Relax and unwind in the scenic surroundings of Riviera Park, a lush green oasis in the heart of Sochi, offering gardens, ponds, and recreational facilities.', 1, 'riviera_park.png'),
  ('Sochi Arboretum', 12, 'Discover a diverse collection of plants from around the world at Sochi Arboretum, a botanical garden nestled between the sea and the mountains.', 1, 'sochi_arboretum.png'),
  ('Matsesta Spring', 12, 'Experience the healing properties of the natural thermal waters at Matsesta Spring, known for its therapeutic baths and spa treatments.', 1, 'matsesta_spring.png'),
  ('Hollywood Walk of Fame', 13, 'Stroll along the iconic Hollywood Walk of Fame, lined with stars honoring notable celebrities from the entertainment industry.', 1, 'hollywood_walk_of_fame.png'),
  ('Universal Studios Hollywood', 13, 'Experience the magic of movies and TV shows come to life at Universal Studios Hollywood, featuring thrilling rides, shows, and attractions.', 1, 'universal_studios_hollywood.png'),
  ('Santa Monica Pier', 13, 'Enjoy oceanfront fun at Santa Monica Pier, home to an amusement park, aquarium, and iconic Ferris wheel overlooking the Pacific Ocean.', 1, 'santa_monica_pier.png'),
  ('Griffith Observatory', 13, 'Observe the stars and enjoy panoramic views of Los Angeles from Griffith Observatory, a beloved landmark in Griffith Park.', 1, 'griffith_observatory.png'),
  ('Getty Center', 13, 'Explore world-class art collections and stunning architecture at the Getty Center, perched atop a hill overlooking Los Angeles.', 1, 'getty_center.png'),
  ('Wawel Royal Castle', 14, 'Step into Polands royal past at Wawel Royal Castle, a UNESCO World Heritage Site overlooking the Vistula River in Krakow.', 1, 'wawel_castle.png'),
  ('Main Market Square', 14, 'Experience the vibrant atmosphere of Krakows Main Market Square, the largest medieval square in Europe, surrounded by historic buildings and landmarks.', 1, 'main_market_square.png'),
  ('Auschwitz-Birkenau Memorial and Museum', 14, 'Pay tribute to the victims of the Holocaust and learn about one of the darkest chapters in human history at Auschwitz-Birkenau Memorial and Museum.', 1, 'auschwitz_birkenau.png'),
  ('Wieliczka Salt Mine', 14, 'Descend underground and explore the fascinating chambers and sculptures carved from salt at Wieliczka Salt Mine, a UNESCO World Heritage Site near Krakow.', 1, 'wieliczka_salt_mine.png'),
  ('Krakow Old Town', 14, 'Wander through the charming streets and squares of Krakows Old Town, filled with historic churches, museums, and cafes.', 1, 'krakow_old_town.png'),
  ('Gyeongbokgung Palace', 15, 'Step back in time and explore the majestic Gyeongbokgung Palace, the largest and most iconic of Seouls Five Grand Palaces.', 1, 'gyeongbokgung_palace.png'),
  ('Myeongdong', 15, 'Shop till you drop and indulge in delicious street food at Myeongdong, one of Seouls most popular shopping districts.', 1, 'myeongdong.png'),
  ('N Seoul Tower', 15, 'Take in panoramic views of Seoul from the observation decks of N Seoul Tower, located atop Namsan Mountain.', 1, 'n_seoul_tower.png'),
  ('Bukchon Hanok Village', 15, 'Stroll through the traditional alleyways and admire the well-preserved hanok houses of Bukchon Hanok Village, a glimpse into Seouls past.', 1, 'bukchon_hanok_village.png'),
  ('Namdaemun Market', 15, 'Explore the largest traditional market in Seoul, Namdaemun Market, offering a wide variety of goods, from clothing to street food.', 1, 'namdaemun_market.png'),
  ('Grand Palace', 16, 'Marvel at the opulent architecture and intricate details of the Grand Palace, a historic complex that once served as the residence of the Thai kings.', 1, 'grand_palace.png'),
  ('Wat Pho', 16, 'Visit the Temple of the Reclining Buddha at Wat Pho, one of Bangkoks oldest and largest temples, renowned for its giant reclining Buddha statue.', 1, 'wat_pho.png'),
  ('Chatuchak Weekend Market', 16, 'Shop for everything under the sun at Chatuchak Weekend Market, one of the largest outdoor markets in the world, offering a vast array of goods.', 1, 'chatuchak_market.png'),
  ('Chao Phraya River Cruise', 16, 'Cruise along the Chao Phraya River and admire the spectacular views of Bangkoks skyline and landmarks, illuminated at night.', 1, 'chao_phraya_cruise.png'),
  ('Khao San Road', 16, 'Experience the lively atmosphere of Khao San Road, a bustling street known for its budget accommodations, street food, and vibrant nightlife.', 1, 'khao_san_road.png'),
  ('Colosseum', 17, 'Step into the ancient world at the Colosseum, an iconic symbol of Rome and one of the greatest works of Roman architecture and engineering.', 1, 'colosseum.png'),
  ('Vatican City', 17, 'Explore the Vatican City, the spiritual and administrative center of the Roman Catholic Church, home to St. Peters Basilica, the Vatican Museums, and the Sistine Chapel.', 1, 'vatican_city.png'),
  ('Trevi Fountain', 17, 'Make a wish and toss a coin into the Trevi Fountain, a Baroque masterpiece and one of the most famous fountains in the world.', 1, 'trevi_fountain.png'),
  ('Pantheon', 17, 'Marvel at the architectural marvel of the Pantheon, a former Roman temple and one of the best-preserved ancient buildings in Rome.', 1, 'pantheon.png'),
  ('Roman Forum', 17, 'Step back in time and explore the ruins of the Roman Forum, once the political and religious center of ancient Rome.', 1, 'roman_forum.png'),
  ('Sagrada Familia', 18, 'Admire the awe-inspiring architecture of the Sagrada Familia, Antoni Gaudís unfinished masterpiece and a UNESCO World Heritage Site.', 1, 'sagrada_familia.png'),
  ('Park Güell', 18, 'Explore the whimsical Park Güell, a public park filled with colorful mosaic sculptures, playful buildings, and lush gardens, designed by Antoni Gaudí.', 1, 'park_guell.png'),
  ('La Rambla', 18, 'Stroll down the bustling boulevard of La Rambla, lined with street performers, cafes, shops, and markets, in the heart of Barcelona.', 1, 'la_rambla.png'),
  ('Gothic Quarter', 18, 'Wander through the narrow medieval streets and hidden squares of the Gothic Quarter, Barcelonas oldest and most atmospheric neighborhood.', 1, 'gothic_quarter.png'),
  ('Camp Nou', 18, 'Experience the passion of FC Barcelona at Camp Nou, one of the largest football stadiums in the world and home to the renowned football club.', 1, 'camp_nou.png'),
  ('Dishoom', 1, 'Experience the flavors of Bombay at Dishoom, serving delicious Indian cuisine in a stylish setting inspired by the Irani cafes of Mumbai.', 3, 'dishoom.png'),
  ('The Wolseley', 1, 'Indulge in classic European cuisine at The Wolseley, an elegant restaurant housed in a grand Art Deco building near Piccadilly Circus.', 3, 'the_wolseley.png'),
  ('Hakkasan Mayfair', 1, 'Savor contemporary Cantonese cuisine at Hakkasan Mayfair, a Michelin-starred restaurant known for its chic ambiance and innovative dishes.', 3, 'hakkasan_mayfair.png'),
  ('Sukiyabashi Jiro', 2, 'Embark on a culinary journey at Sukiyabashi Jiro, a renowned sushi restaurant with three Michelin stars, famously featured in the documentary "Jiro Dreams of Sushi".', 3, 'sukiyabashi_jiro.png'),
  ('Tonkatsu Maisen Aoyama Honten', 2, 'Indulge in crispy and juicy tonkatsu (breaded pork cutlet) at Tonkatsu Maisen Aoyama Honten, a beloved restaurant with a long history.', 3, 'tonkatsu_maisen.png'),
  ('Narisawa', 2, 'Experience innovative and eco-conscious cuisine at Narisawa, a two-Michelin-starred restaurant led by chef Yoshihiro Narisawa, known for his unique approach to Japanese ingredients.', 3, 'narisawa.png'),
  ('Palkin', 3, 'Dine in a historic setting at Palkin, one of the oldest restaurants in Saint Petersburg, serving traditional Russian cuisine with a touch of elegance.', 3, 'palkin.png'),
  ('Teplo', 3, 'Enjoy cozy ambiance and hearty Russian dishes at Teplo, a charming restaurant located in the heart of Saint Petersburg, near the Church of the Savior on Spilled Blood.', 3, 'teplo.png'),
  ('LEurope Restaurant', 3, 'Experience refined dining at LEurope Restaurant, located within the historic Belmond Grand Hotel Europe, offering European cuisine with a Russian twist.', 3, 'leurope.png'),
  ('Le Bernardin', 4, 'Experience exquisite seafood dining at Le Bernardin, a three-Michelin-starred restaurant renowned for its elegant atmosphere and impeccable service.', 3, 'le_bernardin.png'),
  ('Peter Luger Steak House', 4, 'Indulge in legendary dry-aged steaks at Peter Luger Steak House, a Brooklyn institution serving prime beef since 1887.', 3, 'peter_luger.png'),
  ('Eleven Madison Park', 4, 'Treat yourself to an unforgettable dining experience at Eleven Madison Park, a three-Michelin-starred restaurant known for its innovative cuisine and exceptional service.', 3, 'eleven_madison_park.png'),
  ('Fore Street', 5, 'Savor farm-to-table cuisine at Fore Street, a rustic-chic restaurant in Portland known for its wood-fired cooking and locally sourced ingredients.', 3, 'fore_street.png'),
  ('Eventide Oyster Co.', 5, 'Enjoy a casual seafood experience at Eventide Oyster Co., where you can indulge in fresh oysters, lobster rolls, and innovative small plates.', 3, 'eventide_oyster_co.png'),
  ('Duckfat', 5, 'Treat yourself to gourmet comfort food at Duckfat, known for its Belgian-style fries cooked in duck fat, creative sandwiches, and house-made desserts.', 3, 'duckfat.png'),
  ('U Kucharzy', 6, 'Dine in a historic cellar at U Kucharzy, a traditional Polish restaurant in Warsaw known for its hearty dishes, friendly atmosphere, and live cooking shows.', 3, 'u_kucharzy.png'),
  ('Platter by Karol Okrasa', 6, 'Experience modern Polish cuisine with a creative twist at Platter by Karol Okrasa, a Michelin-starred restaurant offering innovative tasting menus.', 3, 'platter.png'),
  ('Warsaw Tortilla Factory', 6, 'Enjoy Mexican-inspired cuisine with a Polish touch at Warsaw Tortilla Factory, where you can savor delicious tacos, burritos, and cocktails.', 3, 'tortilla_factory.png'),
  ('Café Pushkin', 7, 'Step into a bygone era at Café Pushkin, a legendary restaurant in Moscow housed in a historic mansion, serving Russian classics with a refined touch.', 3, 'cafe_pushkin.png'),
  ('White Rabbit', 7, 'Experience elevated Russian cuisine with a modern twist at White Rabbit, a stylish restaurant with panoramic views of Moscow from its glass dome.', 3, 'white_rabbit.png'),
  ('Grand Café Dr. Zhivago', 7, 'Dine in elegance at Grand Café Dr. Zhivago, located in the historic Hotel National and offering a menu of Russian and European dishes.', 3, 'dr_zhivago.png'),
  ('Kikunoi', 8, 'Embark on a culinary journey of kaiseki cuisine at Kikunoi, a Michelin-starred restaurant in Kyoto known for its exquisite presentation and seasonal ingredients.', 3, 'kikunoi.png'),
  ('Izusen', 8, 'Experience shojin ryori (Zen Buddhist vegetarian cuisine) at Izusen, located within Daitokuji Temple in Kyoto and offering a serene dining experience.', 3, 'izusen.png'),
  ('Ganko Sushi', 8, 'Indulge in traditional Kyoto-style sushi at Ganko Sushi, where you can taste the freshest seafood and savor the flavors of the region.', 3, 'ganko_sushi.png'),
  ('Korchma Taras Bulba', 9, 'Experience Ukrainian cuisine with a cozy atmosphere at Korchma Taras Bulba, offering traditional dishes and live music performances.', 3, 'korchma_taras_bulba.png'),
  ('Gogi Ramen', 9, 'Warm up with a comforting bowl of ramen at Gogi Ramen, a popular spot in Vladimir known for its rich broth and customizable toppings.', 3, 'gogi_ramen.png'),
  ('Mishka Pub', 9, 'Unwind with craft beer and pub grub at Mishka Pub, a laid-back establishment in Vladimir where you can enjoy drinks with friends in a relaxed setting.', 3, 'mishka_pub.png'),
  ('The Witchery by the Castle', 10, 'Dine in historic splendor at The Witchery by the Castle, a lavish restaurant housed in a 16th-century building near Edinburgh Castle, serving Scottish cuisine with a touch of luxury.', 3, 'the_witchery.png'),
  ('The Kitchin', 10, 'Experience modern Scottish cuisine with French influences at The Kitchin, a Michelin-starred restaurant led by chef Tom Kitchin, known for its seasonal tasting menus and emphasis on local ingredients.', 3, 'the_kitchin.png'),
  ('The Dome', 10, 'Indulge in grandeur at The Dome, an iconic Edinburgh institution located in a former bank building, offering elegant dining spaces and a menu of classic dishes.', 3, 'the_dome.png'),
  ('Kani Doraku', 11, 'Savor the flavors of Osaka at Kani Doraku, a renowned restaurant specializing in crab dishes, including grilled crab, crab sushi, and crab hot pot.', 3, 'kani_doraku.png'),
  ('Mizuno', 11, 'Treat yourself to savory okonomiyaki (Japanese savory pancake) at Mizuno, a popular restaurant in Osaka known for its customizable and delicious creations.', 3, 'mizuno.png'),
  ('Kuromon Ichiba Market', 11, 'Experience a culinary adventure at Kuromon Ichiba Market, where you can sample a wide variety of street food, fresh seafood, and local delicacies.', 3, 'kuromon_market.png'),
  ('Gorki Plaza', 12, 'Enjoy international cuisine and panoramic views at Gorki Plaza, a stylish restaurant located in the Gorky Gorod mountain resort area of Sochi.', 3, 'gorki_plaza.png'),
  ('Barkhatnyye Sezony', 12, 'Dine in elegance at Barkhatnyye Sezony, a fine dining restaurant in Sochi known for its upscale ambiance, attentive service, and creative dishes.', 3, 'barkhatnyye_sezony.png'),
  ('Black Sea Deli', 12, 'Sample delicious Caucasian cuisine at Black Sea Deli, a cozy restaurant in Sochi offering a variety of dishes inspired by the flavors of the region.', 3, 'black_sea_deli.png'),
  ('In-N-Out Burger', 13, 'Satisfy your cravings with a classic burger and fries at In-N-Out Burger, a beloved fast-food chain known for its fresh ingredients and secret menu options.', 3, 'innout_burger.png'),
  ('République', 13, 'Experience French-inspired cuisine with a California twist at République, a popular restaurant housed in a historic building in Los Angeles, known for its artisanal bread and pastries.', 3, 'republique.png'),
  ('Bestia', 13, 'Indulge in rustic Italian cuisine at Bestia, a hip restaurant in the Arts District of Los Angeles, known for its house-made charcuterie, wood-fired pizzas, and inventive pasta dishes.', 3, 'bestia.png'),
  ('Pod Wawelem', 14, 'Dine in a historic cellar at Pod Wawelem, a traditional Polish restaurant in Krakow known for its hearty pierogi, roasted meats, and cozy ambiance.', 3, 'pod_wawelem.png'),
  ('Miodova', 14, 'Experience Jewish cuisine at Miodova, a charming restaurant in Krakows Kazimierz district, serving traditional dishes such as matzo ball soup, gefilte fish, and brisket.', 3, 'miodova.png'),
  ('Plac Nowy 1', 14, 'Enjoy contemporary Polish cuisine at Plac Nowy 1, a stylish restaurant located in the heart of Krakows Jewish Quarter, offering creative interpretations of classic dishes.', 3, 'plac_nowy_1.png'),
  ('Jungsik', 15, 'Experience modern Korean cuisine with a creative twist at Jungsik, a Michelin-starred restaurant in Seoul known for its innovative tasting menus and elegant presentation.', 3, 'jungsik.png'),
  ('Gwangjang Market', 15, 'Embark on a culinary adventure at Gwangjang Market, one of Seouls oldest and largest markets, offering a wide variety of street food, snacks, and traditional Korean dishes.', 3, 'gwangjang_market.png'),
  ('Gaeseong Mandu Koong', 15, 'Sample delicious mandu (Korean dumplings) at Gaeseong Mandu Koong, a popular restaurant in Seoul known for its handcrafted dumplings filled with flavorful ingredients.', 3, 'gaeseong_mandu_koong.png'),
  ('Thip Samai', 16, 'Taste the best pad Thai in Bangkok at Thip Samai, a legendary restaurant known for its flavorful noodles, served with fresh shrimp, tofu, or crab.', 3, 'thip_samai.png'),
  ('Som Tum Der', 16, 'Indulge in authentic Isaan cuisine at Som Tum Der, where you can enjoy spicy papaya salad, grilled meats, and other northeastern Thai specialties.', 3, 'som_tum_der.png'),
  ('Jay Fai', 16, 'Experience Michelin-starred street food at Jay Fai, a renowned restaurant where you can watch the talented owner-chef cook up delicious crab omelets and other Thai favorites over charcoal fires.', 3, 'jay_fai.png'),
  ('Trattoria Da Danilo', 17, 'Dine like a local at Trattoria Da Danilo, a family-run restaurant in Rome known for its hearty Roman cuisine, including classic pasta dishes, grilled meats, and seasonal specialties.', 3, 'da_danilo.png'),
  ('Pizzeria Baffetto', 17, 'Savor authentic Roman-style pizza at Pizzeria Baffetto, a bustling pizzeria near Piazza Navona, where you can enjoy thin-crust pizzas with fresh toppings.', 3, 'pizzeria_baffetto.png'),
  ('Roscioli', 17, 'Experience a gastronomic journey at Roscioli, a renowned deli and restaurant in Rome known for its high-quality meats, cheeses, and freshly baked bread, as well as its delicious pasta dishes and wine selection.', 3, 'roscioli.png'),
  ('Tickets', 18, 'Embark on a culinary adventure at Tickets, a whimsical tapas bar in Barcelona owned by renowned chef Ferran Adrià, where you can enjoy creative small plates and innovative cocktails in a lively atmosphere.', 3, 'tickets.png'),
  ('Ciudad Condal', 18, 'Taste a variety of delicious tapas at Ciudad Condal, a bustling tapas bar in Barcelona known for its extensive menu, featuring classic Spanish dishes such as patatas bravas, jamón ibérico, and grilled seafood.', 3, 'ciudad_condal.png'),
  ('Bar Canete', 18, 'Experience traditional Catalan cuisine with a modern twist at Bar Canete, a popular restaurant in Barcelona offering an array of seafood, meat, and vegetable dishes, as well as an impressive selection of wines and cocktails.', 3, 'bar_canete.png'),
  ('The Ritz London', 1, 'Experience luxury at The Ritz London, an iconic hotel in the heart of Mayfair, offering elegant accommodations, fine dining, and impeccable service.', 2, 'ritz_london.png'),
  ('The Savoy', 1, 'Indulge in timeless elegance at The Savoy, a historic hotel on the banks of the River Thames, known for its luxurious rooms, award-winning restaurants, and famous American Bar.', 2, 'the_savoy.png'),
  ('Shangri-La Hotel at The Shard', 1, 'Enjoy breathtaking views of London from the Shangri-La Hotel at The Shard, located in one of the citys most iconic skyscrapers, offering luxurious rooms, Michelin-starred dining, and a serene spa.', 2, 'shangri_la_london.png'),
  ('Park Hyatt Tokyo', 2, 'Experience urban luxury at Park Hyatt Tokyo, located in the heart of Shinjuku, offering stylish rooms, panoramic views of the city, and world-class dining.', 2, 'park_hyatt_tokyo.png'),
  ('The Peninsula Tokyo', 2, 'Indulge in refined luxury at The Peninsula Tokyo, a five-star hotel in Marunouchi, known for its elegant accommodations, impeccable service, and exquisite dining options.', 2, 'peninsula_tokyo.png'),
  ('Hotel Chinzanso Tokyo', 2, 'Escape to a tranquil oasis at Hotel Chinzanso Tokyo, nestled in a lush garden setting in Bunkyo, offering spacious rooms, serene gardens, and a range of dining options.', 2, 'hotel_chinzanso_tokyo.png'),
  ('Four Seasons Hotel Lion Palace St. Petersburg', 3, 'Experience grandeur at Four Seasons Hotel Lion Palace St. Petersburg, located within a historic palace near the Hermitage Museum, offering luxurious accommodations, fine dining, and a tranquil courtyard.', 2, 'four_seasons_st_petersburg.png'),
  ('Belmond Grand Hotel Europe', 3, 'Indulge in old-world charm at Belmond Grand Hotel Europe, a landmark hotel on Nevsky Prospekt, known for its elegant rooms, historic ambiance, and gourmet dining options.', 2, 'grand_hotel_europe.png'),
  ('Corinthia Hotel St. Petersburg', 3, 'Discover luxury at Corinthia Hotel St. Petersburg, a modern hotel on Nevsky Prospekt, offering spacious rooms, a spa with a panoramic view, and a range of dining options.', 2, 'corinthia_st_petersburg.png'),
  ('The Plaza Hotel', 4, 'Experience timeless elegance at The Plaza Hotel, an iconic landmark on Fifth Avenue, offering luxurious rooms, world-class dining, and a legendary Palm Court.', 2, 'plaza_hotel_nyc.png'),
  ('The St. Regis New York', 4, 'Indulge in sophistication at The St. Regis New York, a historic hotel on Fifth Avenue, known for its elegant accommodations, bespoke service, and the iconic King Cole Bar.', 2, 'st_regis_nyc.png'),
  ('The Langham, New York, Fifth Avenue', 4, 'Discover luxury at The Langham, New York, Fifth Avenue, a modern hotel near Bryant Park, offering stylish rooms, a tranquil spa, and fine dining at Michelin-starred Ai Fiori.', 2, 'langham_nyc.png'),
  ('The Cliff House Resort & Spa', 5, 'Experience coastal luxury at The Cliff House Resort & Spa, perched atop Bald Head Cliff in Cape Neddick, offering stunning ocean views, luxurious accommodations, and a serene spa.', 2, 'cliff_house_maine.png'),
  ('Portland Harbor Hotel', 5, 'Indulge in urban charm at Portland Harbor Hotel, located in the heart of Portlands Old Port district, offering stylish rooms, a cozy fireplace lounge, and convenient access to the citys attractions.', 2, 'portland_harbor_hotel.png'),
  ('The Press Hotel, Autograph Collection', 5, 'Discover boutique luxury at The Press Hotel, a historic property in Portlands Old Port district, offering chic accommodations inspired by its former life as a newspaper headquarters.', 2, 'press_hotel_maine.png'),
  ('Hotel Bristol, a Luxury Collection Hotel, Warsaw', 6, 'Experience timeless elegance at Hotel Bristol, a Luxury Collection Hotel, Warsaw, a historic landmark on Krakowskie Przedmieście, offering luxurious rooms, fine dining, and impeccable service.', 2, 'hotel_bristol_warsaw.png'),
  ('InterContinental Warsaw', 6, 'Indulge in modern luxury at InterContinental Warsaw, a sleek hotel in the city center, offering spacious rooms, panoramic views, and a range of dining options, including a rooftop restaurant.', 2, 'intercontinental_warsaw.png'),
  ('Raffles Europejski Warsaw', 6, 'Discover refined luxury at Raffles Europejski Warsaw, a legendary hotel on Krakowskie Przedmieście, known for its elegant accommodations, historic ambiance, and world-class dining.', 2, 'raffles_europejski_warsaw.png'),
  ('The Ritz-Carlton, Moscow', 7, 'Experience luxury at The Ritz-Carlton, Moscow, located just steps from Red Square and the Kremlin, offering elegant rooms, world-class dining, and a rooftop terrace with panoramic views of the city.', 2, 'ritz_carlton_moscow.png'),
  ('Four Seasons Hotel Moscow', 7, 'Indulge in sophistication at Four Seasons Hotel Moscow, a modern hotel near Red Square, offering luxurious accommodations, a rooftop pool, and a range of dining options, including Italian cuisine at Quadrum.', 2, 'four_seasons_moscow.png'),
  ('Ararat Park Hyatt Moscow', 7, 'Discover contemporary luxury at Ararat Park Hyatt Moscow, a stylish hotel overlooking the Bolshoi Theatre, offering spacious rooms, a spa with an indoor pool, and fine dining at The Conservatory.', 2, 'ararat_park_hyatt_moscow.png'),
  ('The Ritz-Carlton, Kyoto', 8, 'Experience tranquility at The Ritz-Carlton, Kyoto, located on the banks of the Kamogawa River, offering luxurious accommodations, traditional tea ceremonies, and exquisite dining options, including Japanese kaiseki cuisine.', 2, 'ritz_carlton_kyoto.png'),
  ('Hoshinoya Kyoto', 8, 'Indulge in a serene ryokan experience at Hoshinoya Kyoto, nestled in the Arashiyama bamboo forest, offering traditional Japanese accommodations, natural hot spring baths, and gourmet kaiseki meals.', 2, 'hoshinoya_kyoto.png'),
  ('Hotel Granvia Kyoto', 8, 'Discover modern luxury at Hotel Granvia Kyoto, located within Kyoto Station, offering convenient access to the citys attractions, spacious rooms, and a variety of dining options, including Japanese, Italian, and French cuisine.', 2, 'hotel_granvia_kyoto.png'),
  ('Vladimir Hotel', 9, 'Experience comfort and convenience at Vladimir Hotel, located in the heart of Vladimir, offering cozy rooms, a restaurant serving Russian and European cuisine, and easy access to the citys attractions.', 2, 'vladimir_hotel.png'),
  ('Golden Ring Hotel', 9, 'Indulge in modern amenities at Golden Ring Hotel, a contemporary hotel in Vladimirs city center, offering stylish accommodations, a rooftop terrace with panoramic views, and a range of dining options.', 2, 'golden_ring_hotel.png'),
  ('Park Hotel Voznesenskaya Sloboda', 9, 'Escape to a peaceful retreat at Park Hotel Voznesenskaya Sloboda, located in a historic estate on the outskirts of Vladimir, offering comfortable rooms, beautiful gardens, and a restaurant serving Russian cuisine.', 2, 'park_hotel_voznesenskaya_sloboda.png'),
  ('The Balmoral Hotel', 10, 'Experience luxury and tradition at The Balmoral Hotel, a historic landmark in the heart of Edinburgh, offering elegant rooms, a Michelin-starred restaurant, and a serene spa.', 2, 'balmoral_hotel.png'),
  ('Sheraton Grand Hotel & Spa', 10, 'Indulge in modern luxury at Sheraton Grand Hotel & Spa, located in the shadow of Edinburgh Castle, offering stylish accommodations, a rooftop hydro pool, and a range of dining options, including Scottish cuisine at One Square.', 2, 'sheraton_grand_hotel_edinburgh.png'),
  ('The Witchery by the Castle (Hotel)', 10, 'Stay in opulent surroundings at The Witchery by the Castle, a historic hotel in Edinburghs Old Town, offering lavish suites, Gothic-inspired decor, and a romantic restaurant serving Scottish cuisine.', 2, 'witchery_hotel_edinburgh.png'),
  ('The Ritz-Carlton, Osaka', 11, 'Experience luxury at The Ritz-Carlton, Osaka, located in the heart of the citys prestigious Nishi-Umeda district, offering spacious accommodations, exceptional service, and a range of dining options, including Michelin-starred French cuisine at La Baie.', 2, 'ritz_carlton_osaka.png'),
  ('InterContinental Osaka', 11, 'Indulge in modern luxury at InterContinental Osaka, a sleek hotel near Umeda Station, offering stylish rooms, panoramic views of the city, and a variety of dining options, including Japanese cuisine at Noka Roast & Grill.', 2, 'intercontinental_osaka.png'),
  ('The St. Regis Osaka', 11, 'Discover sophistication at The St. Regis Osaka, located in the vibrant Midosuji district, offering elegant accommodations, personalized butler service, and exquisite dining options, including authentic Italian cuisine at La Veduta.', 2, 'st_regis_osaka.png'),
  ('Radisson Blu Resort & Congress Centre, Sochi', 12, 'Experience seaside luxury at Radisson Blu Resort & Congress Centre, Sochi, located on the shores of the Black Sea, offering modern accommodations, a private beach, and a range of recreational facilities, including a spa and tennis courts.', 2, 'radisson_blur_sochi.png'),
  ('Swissôtel Resort Sochi Kamelia', 12, 'Indulge in relaxation at Swissôtel Resort Sochi Kamelia, nestled in a lush subtropical park, offering stylish rooms, a private beach, and a variety of dining options, including Mediterranean cuisine at Barkhatnye Sezony.', 2, 'swissotel_sochi.png'),
  ('Hyatt Regency Sochi', 12, 'Discover coastal luxury at Hyatt Regency Sochi, located in the heart of the city, offering spacious rooms with sea views, a rooftop pool, and a range of dining options, including European cuisine at Belcanto Restaurant.', 2, 'hyatt_regency_sochi.png'),
  ('The Ritz-Carlton, Los Angeles', 13, 'Experience luxury at The Ritz-Carlton, Los Angeles, located in the heart of downtown LA, offering elegant accommodations, a rooftop pool with panoramic views, and fine dining at WP24 by Wolfgang Puck.', 2, 'ritz_carlton_los_angeles.png'),
  ('InterContinental Los Angeles Downtown', 13, 'Indulge in modern luxury at InterContinental Los Angeles Downtown, a sleek skyscraper hotel offering stylish rooms, panoramic views of the city, and a variety of dining options, including French cuisine at La Boucherie.', 2, 'intercontinental_los_angeles.png'),
  ('The London West Hollywood at Beverly Hills', 13, 'Discover chic luxury at The London West Hollywood at Beverly Hills, offering spacious suites, a rooftop pool with stunning views of the LA skyline, and upscale dining at Boxwood Restaurant.', 2, 'london_west_hollywood.png'),
  ('Hotel Copernicus', 14, 'Experience historic charm at Hotel Copernicus, a boutique hotel in the heart of Krakows Old Town, offering elegant rooms, a rooftop terrace with panoramic views, and a restaurant serving Polish and international cuisine.', 2, 'hotel_copernicus.png'),
  ('Hotel Stary', 14, 'Indulge in luxury at Hotel Stary, located in a 15th-century tenement house, offering stylish rooms, a rooftop swimming pool, and a range of dining options, including fine dining at Trzy Rybki.', 2, 'hotel_stary.png'),
  ('Sheraton Grand Krakow', 14, 'Discover modern comfort at Sheraton Grand Krakow, situated on the banks of the Vistula River, offering spacious rooms, a rooftop terrace with panoramic views, and a variety of dining options, including Polish cuisine at The Olive Restaurant.', 2, 'sheraton_grand_krakow.png'),
  ('The Shilla Seoul', 15, 'Experience luxury at The Shilla Seoul, a five-star hotel in the heart of the city, offering elegant rooms, a world-class spa, and a variety of dining options, including Korean, Japanese, and Chinese cuisine.', 2, 'shilla_seoul.png'),
  ('Lotte Hotel Seoul', 15, 'Indulge in sophistication at Lotte Hotel Seoul, located in the bustling Myeongdong district, offering luxurious accommodations, a duty-free shopping mall, and a range of dining options, including international cuisine at La Seine.', 2, 'lotte_hotel_seoul.png'),
  ('Grand Hyatt Seoul', 15, 'Discover urban luxury at Grand Hyatt Seoul, nestled on the slopes of Mount Namsan, offering spacious rooms, panoramic views of the city, and a variety of dining options, including Italian cuisine at Terrace.', 2, 'grand_hyatt_seoul.png'),
  ('The Peninsula Bangkok', 16, 'Experience riverside luxury at The Peninsula Bangkok, located on the banks of the Chao Phraya River, offering luxurious accommodations, a three-tiered swimming pool, and fine dining at Mei Jiang.', 2, 'peninsula_bangkok.png'),
  ('Mandarin Oriental, Bangkok', 16, 'Indulge in timeless elegance at Mandarin Oriental, Bangkok, a legendary hotel on the banks of the Chao Phraya River, offering luxurious accommodations, world-class dining, and a tranquil spa.', 2, 'mandarin_oriental_bangkok.png'),
  ('Anantara Siam Bangkok Hotel', 16, 'Discover urban oasis at Anantara Siam Bangkok Hotel, located in the heart of the citys shopping and business district, offering elegant rooms, a spa with traditional Thai treatments, and a variety of dining options, including Thai cuisine at Spice Market.', 2, 'anantara_siam_bangkok.png'),
  ('Hotel Hassler Roma', 17, 'Experience luxury and elegance at Hotel Hassler Roma, a historic landmark overlooking the Spanish Steps, offering luxurious accommodations, Michelin-starred dining, and breathtaking views of Rome.', 2, 'hassler_roma.png'),
  ('Grand Hotel de la Minerve', 17, 'Indulge in timeless luxury at Grand Hotel de la Minerve, located in the heart of Rome near the Pantheon, offering elegant rooms, a rooftop terrace with panoramic views, and a variety of dining options.', 2, 'grand_hotel_minerve.png'),
  ('Rome Cavalieri, A Waldorf Astoria Hotel', 17, 'Discover grandeur at Rome Cavalieri, A Waldorf Astoria Hotel, situated on a hill overlooking the city, offering opulent accommodations, a luxury spa, and gourmet dining at Michelin-starred La Pergola.', 2, 'rome_cavalieri.png'),
  ('Hotel Arts Barcelona', 18, 'Experience contemporary luxury at Hotel Arts Barcelona, located on the waterfront near Barceloneta Beach, offering stylish accommodations, a rooftop pool, and Michelin-starred dining at Enoteca Paco Pérez.', 2, 'hotel_arts_barcelona.png'),
  ('Majestic Hotel & Spa Barcelona', 18, 'Indulge in elegance at Majestic Hotel & Spa Barcelona, a historic hotel on Passeig de Gràcia, offering luxurious rooms, a rooftop terrace with panoramic views, and a variety of dining options, including Mediterranean cuisine at El Patio del Majestic.', 2, 'majestic_hotel_barcelona.png'),
  ('Hotel Casa Fuster', 18, 'Discover modernist luxury at Hotel Casa Fuster, a landmark hotel in the heart of Barcelonas Eixample district, offering stylish accommodations, a rooftop terrace, and gourmet dining at Café Vienés.', 2, 'casa_fuster_barcelona.png');
"""

# Разделение запроса на строки
rows = query.split("\n")[1:-1] # Пропускаем первую и последнюю пустую строку

# Проход по каждой строке и замена пути к изображению на уникальный код
def change_image_path(query):
    lines = query.strip().split('\n')
    new_query = ""
    for line in lines:
        parts = line.strip().split(',')
        unique_code = str(uuid.uuid4()) + ".png"  # генерируем уникальный код
        parts[-2] = f"'{unique_code}'"  # заменяем путь на уникальный код
        new_line = ', '.join(parts) + '),'
        new_query += new_line + '\n'
    return new_query.strip()

# Применяем функцию к запросу
new_query = change_image_path(query)
print(new_query)
